# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
       - '[0-9]+.[0-9]+.[0-9]+'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: flutter pub publish --force